### ISSUE TITLE
Go言語でつくったアプリの自動ビルドやテストについて調べる

### ISSUE THREAD

**Issue by fujimiyanatsuki** [fujimiyanatsuki/til#1]

**Comment by fujimiyanatsuki** [comment]
# GPT4に聞いた結果

※聞いただけなのでまだどこまで本当かは調べてない

GitHub上でのアプリケーションの自動ビルドとテストを実行するためには、GitHub Actionsを利用するのが一般的です。GitHub Actionsは、リポジトリにpushされたコードのビルドやテスト、デプロイなどを自動化するためのCI/CDツールです。以下に、Goで作成されたアプリケーションの自動ビルドとテストを設定する基本的な手順を示します。

1. **リポジトリの準備**:
   - GitHub上にリポジトリを作成し、Goで作成されたアプリケーションのソースコードをpushします。

2. **GitHub Actionsの設定ファイル作成**:
   - リポジトリのルートに`.github/workflows`ディレクトリを作成します。
   - そのディレクトリ内に、例えば`go.yml`という名前でYAMLファイルを作成します。

```yaml
name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go mod download

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
```

3. **GitHub Actionsの設定ファイルをコミットおよびプッシュ**:
   - 作成した`go.yml`ファイルをgitにコミットし、GitHubのリポジトリにプッシュします。

4. **アクションの実行**:
   - GitHubリポジトリにプッシュすると、GitHub Actionsが自動的にビルドとテストのジョブを実行します。結果はGitHubのリポジトリページ上で確認できます。

この設定ファイルは基本的な例であり、プロジェクトの要件に応じてカスタマイズすることが可能です。ビルドやテストの手順を変更したり、追加のジョブやステップを定義することで、より複雑なCI/CDパイプラインを構築することもできます。
